version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sufian_hamza
      POSTGRES_PASSWORD: russ3509
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp: